### Python类动态调用函数

In [ ]:
import struct
from types import MethodType

class Cat(object):
    def __int__(self):
        super().__init__()

def run(self):
    print('cat is running!')

def main():
    cat01 = Cat()
    cat01.run = MethodType(run, cat01)
    cat01.run()

if __name__ == '__main__':
    main()

### Python多线程

In [9]:
import datetime
import time
import threading

class Mythread01(threading.Thread):
    def __init__(self):
        super(Mythread01, self).__init__()
    def run(self):
        while True:
            now_time = datetime.datetime.now()
            print(now_time)
            time.sleep(1)

class Mythread02(threading.Thread):
    def __init__(self):
        super(Mythread02, self).__init__()
    def run(self):
        while True:
            print("张三")
            time.sleep(0.5)
def main():
    mt01 = Mythread01()
    mt01.start()
    mt02 = Mythread02()
    mt02.start()

if __name__=="__main__":
    main()

2023-02-23 14:15:06.869261
张三


### 线程定时器使用

In [20]:
import datetime
import threading

def run():
    print(datetime.datetime.now())
    r_t01 = threading.Timer(1, run)
    r_t01.start()

if __name__ ==  '__main__':
    t01 = threading.Thread(target=run)
    t01.start()

2023-02-23 14:54:04.346092
2023-02-23 14:54:04.352784
2023-02-23 14:54:04.352784
2023-02-23 14:54:04.445138
2023-02-23 14:54:04.445765
2023-02-23 14:54:04.488039


### 列表排序

In [18]:
cars = ['bmw', 'audi', 'toyota', 'subaru']
cars.sort()  # 升序
print('默认升序： ', cars)
cars.sort(reverse=True) # 降序
print('降序： ', cars)

temp_cars = sorted(cars)  # 临时升序
print('排序后返回新列表', temp_cars)
print('old cars', cars)

默认升序：  ['audi', 'bmw', 'subaru', 'toyota']
降序：  ['toyota', 'subaru', 'bmw', 'audi']
排序后返回新列表 ['audi', 'bmw', 'subaru', 'toyota']
old cars ['toyota', 'subaru', 'bmw', 'audi']


In [60]:
num =  [i for i in range(1, 11)]
print('构造列表：', num)
num.reverse()
print('反转列表：', num)
new_num = list(reversed(num))
print('生成新的反转列表：', new_num)

构造列表： [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
反转列表： [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


TypeError: 'list' object is not callable

### 切片

In [61]:
even_numbers = list(range(2,11,2))
print(even_numbers)
print(even_numbers[:3])
print(even_numbers[-3:])
print(even_numbers[0:-2])
print('步长为-1切片：列表反转', even_numbers[::-1])
print('步长为-2切片：', even_numbers[::-2])
print('步长为2切片：', even_numbers[::2])

TypeError: 'list' object is not callable

### 内部函数

In [7]:
some_list = ['foo', 'bar', 'baz']
mapping = {}
for i,v in enumerate(some_list):
    mapping[i] = v
mapping

{0: 'foo', 1: 'bar', 2: 'baz'}

In [95]:
import re
states = ['  Alabab ', 'baidu@#!', 'teng%$@!xun']
def remove_punctutation(value):
    return  re.sub('[!#?@%$" "]', '', value)
for x in map(remove_punctutation, states):
    print(x)


Alabab
baidu
tengxun


In [105]:
# 匿名函数 没有__name__属性
equiv_anon = lambda y: y * 2
print(equiv_anon(10))

strings = ['foo', 'card', 'bar', 'aaa']
strings.sort(key=lambda k: len(set(list(k))))
print(strings)

20
['aaa', 'foo', 'bar', 'card']


In [50]:
foo = [-5, 8, 0, 4, 9, -20, -2, 3, -6, 32]
a = sorted(foo, key=lambda x:(x<-1, abs(x)))
print(a)

[0, 3, 4, 8, 9, 32, -2, -5, -6, -20]


In [51]:
s = ['a', 'dfgfrty', 'ssdf', 'asd']
sort_s = sorted(s, key=lambda x: len(x))
print(sort_s)

['a', 'asd', 'ssdf', 'dfgfrty']


In [ ]:
s = 'sgjqsafgxvyiomsadf'
s = set(s)
l = list(s)
l.sort()
res = ''.join(l)
print(res)

In [109]:
# 生成器表达式
sum_value = sum(x ** 2 for x in range(10))
print(sum_value)

dict_value = dict((i, i **2) for i in range(5))
print(dict_value)

285
{0: 0, 1: 1, 2: 4, 3: 9, 4: 16}


### 将列表、元组或其他序列元素配对，新建一个元组构成列表

In [55]:
seq1 = ['one', 'two', 'three']
seq2 = ['foo', 'bar', 'baz']
zipped = zip(seq1, seq2)
zipped_list = list(zipped)
print(zipped_list)
nums, names = zip(*zipped_list)
nums, names


TypeError: 'list' object is not callable

### 字典

In [29]:
mapping = {}
seq1 = ['one', 'two', 'three']
seq2 = ['foo', 'bar', 'baz']
for key, value in zip(seq1, seq2):
    mapping[key] = value
mapping

{'one': 'foo', 'two': 'bar', 'three': 'baz'}

In [38]:
mapping = dict(zip(range(5), reversed(range(1, 6))))
mapping

{0: 5, 1: 4, 2: 3, 3: 2, 4: 1}

In [110]:
# value = some_dict.get(key, default_value)

by_letter = {}
words = ['appale', 'bat', 'bar', 'cook']
for word in words:
    letter = word[0]
    by_letter.setdefault(letter,[]).append(word)
by_letter

{'a': ['appale'], 'b': ['bat', 'bar'], 'c': ['cook']}

In [54]:
# 字典根据键从小到大排序
dict = {'name': 'ZS', 'age': 18, 'city': '深圳', 'tel': '13748727649'}
# e表示dict.items()中的一个元素，e[1],则表示按值排序,如果把e[1]改成e[0],那么则是按键排序
lists = sorted(dict.items(), key=lambda e:e[0], reverse=False)
print('sorted根据字典建排序：', lists)

sorted根据字典建排序： [('age', 18), ('city', '深圳'), ('name', 'ZS'), ('tel', '13748727649')]


### 列表推导式

In [53]:
strings = ['a', 'book', 'car', 'bat']
mapping =  [x.upper() for x in strings if len(x) > 3]
print(mapping)
loc_mapping = {index: val for index, val in enumerate(strings)}
print(loc_mapping)

['BOOK']
{0: 'a', 1: 'book', 2: 'car', 3: 'bat'}


In [62]:
# 嵌套列表推导式
strings = [['a', 'book'], ['car', 'bat']]
result = [name for names in strings for name in names if name.count('a') >= 1]
result

['a', 'car', 'bat']

In [56]:
lists = [i for i in range(1,6)]
result = map(lambda x: x**2, lists)
result = [i for i in result if i > 10]
result

[16, 25]

In [58]:
a = ['苏州', '中国', '哈哈', '','日本', '','英国']
res = list(map(lambda x:'无数据' if x=='' else x,a))
print(res)

TypeError: 'list' object is not callable

In [36]:
a = [i for i in range(1,11)]
res = [i for i in a if i%2==1]
print(res)

a = [i for i in range(1,11)]
newlist = filter(lambda x: x%2==1, a)
newlist = [i for i in newlist]
print(newlist)

[1, 3, 5, 7, 9]
[1, 3, 5, 7, 9]


### 全局变量

In [78]:
a = []
def test():
    global a
    a = [1,2]
test()
print(a)

[1, 2]


In [42]:
import datetime
print(str(datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')) + ' 星期' + str(datetime.datetime.now().isoweekday()))

2023-02-28 14:33:06 星期2


### 正则表达式

In [44]:
# (.*) 贪婪匹配，会把满足正则的尽可能多的往后匹配
# （。*？）非贪婪匹配，会把满足正则的尽可能少匹配
import re
s = '<a>哈哈</a><a>嘿嘿</a>'
res1 = re.findall('<a>(.*)</a>', s)
print('贪婪匹配', res1)
res2 = re.findall('<a>(.*?)</a>', s)
print('非贪婪匹配', res2)

贪婪匹配 ['哈哈</a><a>嘿嘿']
非贪婪匹配 ['哈哈', '嘿嘿']


In [46]:
import re
a = '李俊95分'
ret = re.sub(r'\d+', '100', a)  # \d数字   \D非数字字符
print(ret)
ret = re.sub(r'\D+', '*', a)
print(ret)

李俊100分
*95*


In [52]:
s = 'info:xiaoZhang 23 shanghai'
res = re.split(r':| ', s)
print(res)

['info', 'xiaoZhang', '23', 'shanghai']


### 装饰器

In [62]:
def net_weight(peel):
    def outwrapper(f):
        def wrapper(*args, **kwargs):
            now_weight = f(*args, **kwargs)
            return now_weight-peel
        return wrapper
    return outwrapper

@net_weight(5)
def weight(n):
    return n
print(weight(160))


155


In [66]:
def my_decorator(func):
    def wrapper():
        print("Something is happening before the function is called.")
        func()
        print("Something is happening after the function is called.")
    return wrapper

@my_decorator
def say_whee():
    print("Whee!")

say_whee()

Something is happening before the function is called.
Whee!
Something is happening after the function is called.


In [82]:
def do_twice(func):
    def wrapper_do_twice(*args, **kwargs):
        func(*args, **kwargs)
        func(*args, **kwargs)
    return wrapper_do_twice

@do_twice
def greet(word):
    print("Hello", word)

greet('world')

Hello world
Hello world


In [87]:
from time import sleep, time
def run_time(func):
    def wrapper():
        start = time()
        func()                  # 函数在这里运行
        end = time()
        cost_time = end - start
        print("func three run time {}".format(cost_time))
    return wrapper

@run_time
def fun_one():
    sleep(1)

@run_time
def fun_two():
    sleep(1)

@run_time
def fun_three():
    sleep(1)

fun_one()
fun_two()
fun_three()


func three run time 1.0116841793060303
func three run time 1.0080668926239014
func three run time 1.0161490440368652


In [90]:
def logger(msg=None):
    def run_time(func):
        def wrapper(*args, **kwargs):
            start = time()
            func()                  # 函数在这里运行
            end = time()
            cost_time = end - start
            print("[{}] func three run time {}".format(msg, cost_time))
        return wrapper
    return run_time

@logger(msg="One")
def fun_one():
    sleep(1)

@logger(msg="Two")
def fun_two():
    sleep(1)

@logger(msg="Three")
def fun_three():
    sleep(1)

fun_one()
fun_two()
fun_three()

[One] func three run time 1.0048027038574219
[Two] func three run time 1.0476858615875244
[Three] func three run time 1.123077392578125


### Numpy

In [12]:
import numpy as np
my_arr1 = np.arange(10)
print('10以内数字', my_arr1)

my_arr2 = np.array([6, 8, 11, 56])
print('转换为数组ndarray', my_arr2)

c = np.random.random([2,3])
print('生成2行3列（0，1）之间的随机浮点数', c)

c = np.random.rand(2,3)
print('生成2行3列（0，1）之间的随机浮点数', c)

c = np.random.randn(2,3)
print('从标准正态分布中返回2行3列样本', c)

c = np.random.randint(1,10, 5)
print('生成1和10之间5个随机整数', c)

10以内数字 [0 1 2 3 4 5 6 7 8 9]
转换为数组ndarray [ 6  8 11 56]
生成2行3列（0，1）之间的随机浮点数 [[0.02587001 0.54467509 0.073984  ]
 [0.08708781 0.57657104 0.60002732]]
生成2行3列（0，1）之间的随机浮点数 [[0.28652185 0.24804672 0.77937842]
 [0.62350855 0.19191479 0.50085895]]
从标准正态分布中返回2行3列样本 [[-0.33980926 -0.61895177 -0.51235467]
 [-0.89042735  0.72145948 -0.43739264]]
生成1和10之间5个随机整数 [4 3 5 2 7]


In [29]:
names = np.array(['Bob', 'Will', 'Bob', 'Jason'])
print(names == 'Bob')
data = np.random.randn(4,6)
print(data)
print('names == “Bob”', data[names == 'Bob'])
data[data<0] = 0
print('负数修改为0', data)

[ True False  True False]
[[-1.33960847 -0.22666182  1.23156514 -1.24563695 -0.07125614 -0.30965735]
 [ 0.46874413  1.86304442  0.06595991 -1.52379726 -0.64644101 -2.01346949]
 [ 0.33250802 -1.56745504 -0.28305478  0.63313373  0.07933091 -0.37173916]
 [-1.14582136 -0.27625952  0.38248787  0.45093367  0.72408545 -1.00202403]]
names == “Bob” [[-1.33960847 -0.22666182  1.23156514 -1.24563695 -0.07125614 -0.30965735]
 [ 0.33250802 -1.56745504 -0.28305478  0.63313373  0.07933091 -0.37173916]]
负数修改为0 [[0.         0.         1.23156514 0.         0.         0.        ]
 [0.46874413 1.86304442 0.06595991 0.         0.         0.        ]
 [0.33250802 0.         0.         0.63313373 0.07933091 0.        ]
 [0.         0.         0.38248787 0.45093367 0.72408545 0.        ]]


In [39]:
arr = np.empty((8,4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [50]:
# 数组转置和换轴
arr = np.arange(32).reshape((8,4))
print(arr)
print('转置', arr.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
转置 [[ 0  4  8 12 16 20 24 28]
 [ 1  5  9 13 17 21 25 29]
 [ 2  6 10 14 18 22 26 30]
 [ 3  7 11 15 19 23 27 31]]


In [60]:
# 数组操作
xarr = np.array([1.1, 1.2, 1.3])
yarr = np.array([2.1, 2.2, 2.3])
cond = np.array([True, False, False])
result = np.where(cond, xarr, yarr)
print(result)

arr = np.random.randn(4, 4)
print(arr)
print(arr>0)
print('小于0的置为0', np.where(arr<0, 0, arr))

[1.1 2.2 2.3]
[[-0.29115256  0.39941844  0.21191714  0.33768984]
 [ 0.43897453  0.83862097 -0.1854524   1.24083245]
 [ 0.22088595  0.86535784  0.49284012 -1.58555209]
 [-0.22969013 -0.5346827  -0.97926481 -1.36777828]]
[[False  True  True  True]
 [ True  True False  True]
 [ True  True  True False]
 [False False False False]]
小于0的置为0 [[0.         0.39941844 0.21191714 0.33768984]
 [0.43897453 0.83862097 0.         1.24083245]
 [0.22088595 0.86535784 0.49284012 0.        ]
 [0.         0.         0.         0.        ]]
